### ISSUE TITLE
Compilation and crosscompilation with AES256 option

### ISSUE THREAD

**Issue by TuITeraz** [net-snmp/net-snmp#105]
Hello,
I have a problem with AES256 compilation for arm. I was trying to enable
 --enable-blumenthal-aes 
as you have suggested.

When i compile for arm :
`./configure  --host="arm-linux-gnueabihf" --target="arm-linux-gnueabihf" --with-cc="arm-linux-gnueabihf-gcc" --without-perl-modules --disable-embedded-perl --enable-ipv6 --prefix=/usr/ --with-defaults --enable-new-features --with-default-snmp-version=2 --with-systemd --with-security-modules="usm tsm" --enable-blumenthal-aes --with-transports="DTLSUDP" --with-install-prefix="~/Developer/Net-SNMP/net-snmp-master-arm-aes/package" --with-openssl="~/Developer/Net-SNMP/openssl-1.1.1d/usr/"`

I have received an error message:

`
checking openssl/aes.h usability... no
checking openssl/aes.h presence... no
checking for openssl/aes.h... no
(...)
configure: error: Blumenthal draft requires OpenSSL with AES functions enabled
`

When i have removed
`--host="arm-linux-gnueabihf" --target="arm-linux-gnueabihf" --with-cc="arm-linux-gnueabihf-gcc" `
There is no error message.:
```
checking openssl/aes.h usability... yes
checking openssl/aes.h presence... yes
checking for openssl/aes.h... yes
(...)
checking for AES_cfb128_encrypt... yes
```

But the summary of ./configure still prints only one AES option:
```
  Authentication support:     MD5 SHA1 SHA512 SHA384 SHA256 SHA192
  Encryption support:         DES AES
```

How to compile AES256 into arm version of net-snmp the right way?

**Comment by bvanassche** [comment]
The configure script did not report the supported authentication and encryption modes correctly. A fix has been checked in on the v5.8 and master branches. Please retest.

**Comment by TuITeraz** [comment]
1 of 2 problems is fixed 

When compiling for x86_64 options are fine now ! 👍 
```
  Authentication support:     MD5 SHA1 SHA224 SHA256 SHA384 SHA512
  Encryption support:         DES AES AES128 AES192 AES192C AES256 AES256C
```

Unfortunatelly,
`configure: error: Blumenthal draft requires OpenSSL with AES functions enabled`
still occurs when compiling for arm :(

I'm using the same openssl version and the same command in both cases. But ARM version compiles (configures) only when options
`--enable-blumenthal-aes --with-transports="DTLSUDP"`
are removed from command. Then AES and AES128 are present, but no AES256, which i really need.

Can you help me?

**Comment by bvanassche** [comment]
Please upload the config.log file produced by the cross-compilation process.

**Comment by TuITeraz** [comment]
Ok. Here is the log.:

https://pastebin.com/9Rpv8a9Z

**Comment by bvanassche** [comment]
From config.log:
~~~
In file included from conftest.c:55:0:
/usr/include/openssl/aes.h:55:34: fatal error: openssl/opensslconf.h: No such file or directory
compilation terminated.
~~~
In other words, the configure script looks for OpenSSL headers in /usr/include instead of the directory specified with --with-openssl. Has it already been considered to change ~ into $HOME when configuring Net-SNMP?

**Comment by TuITeraz** [comment]
OK!
Now configuration and compilation works fine :)

I was trying to use snmpd and test AES256 connection, but now i have different error:

```
# snmpd -f -Lo
Agent initialization failed
```
Error message is not specified.

**Comment by bvanassche** [comment]
I think that the "Agent initialization failed" issue was introduced by commit f1647e3db242 ("snmpd: Do not open /dev/kmem on Linux") and also that it was fixed by commit 
59e8b5b28db8 ("snmpd: Make init_kmem() report "success" if /dev/kmem is not opened"). Please update your local copy of the Net-SNMP tree (`git pull --rebase` or `git clone`) and retest.

**Comment by TuITeraz** [comment]
OK. Great! Now it works 👍  
Thank you very much for fast responses!



BTW. Is there any active discussion group, where i can ask questions like these ? Issues aren't probably the best place for this, but i have no idea who else can help me.

1.What is the best way to check (during runtime) if an agentx is connected to master? Right now i was trying to call this:
`agentx_send_ping(main_session);`
but then (when everything is fine, and don't need reconnection) every second it produces log:
`AgentX session to master agent attempted to be re-opened`

2. Registering variables is verry slow. I want to register around 20000 OIDs using 
```
reginfo = netsnmp_create_handler_registration(...);
netsnmp_register_watched_instance2( reginfo, netsnmp_create_watcher_info (...) ) 
```
and it takes around 30sec.  Can i speed it up, or is it possible to register multiple oid/variables/handlers at the same time?

**Comment by bvanassche** [comment]
Please take a look at http://www.net-snmp.org/support/mailinglists.html.
